name: Make TWRP Device

on:
  workflow_dispatch:
    inputs:
      LIBRARY_NAME: 
        description: 'HELLO ACTIONS'
        required: true
        default: ''
      IMG_URL:
        description: 'COW_URL'
        required: true
        default: ''

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04

      
    
