name: Make TWRP Device

on:
  workflow_dispatch:
    inputs:
      LIBRARY_NAME:
        description: 'LIBRARY_NAME'
        required: true
        default: ''
      IMG_URL:
        description: 'COW_URL'
        required: true
        default: ''

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    
    steps:
    - name: Check Out
      uses: actions/checkout@main
      
    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y install python gcc python3 python3-pip python3-pip cpio wget
      
    - name: Set variables
      run: |
        echo "name=date::$(date +%F)" >> $GITHUB_OUTPUT
      id: var
       
              
    - name: Download dirtycow.c      run: |
        wget ${{ github.event.inputs.COW_URL }}
        ls
      
    
