# .github/workflows/create_zip.yml  
name: Create ZIP Archive  
  
on:  
  # 触发条件，比如push到一个特定的分支  
  push:  
    branches: [ main ]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  
  
      - name: Set up Python  
        uses: actions/setup-python@v2  
        with:  
          python-version: 3.x # 或者你需要的任何Python版本  
  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          # 如果你的脚本有依赖，可以在这里安装它们  
  
      - name: Create ZIP file  
        run: |  
          python create_zip.py  
  
      - name: Upload ZIP file as artifact  
        uses: actions/upload-artifact@v2  
        with:  
          name: my-zip-archive  
          path: my_archive.zip
