name: Compile dirtycow 
  
on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
    - uses: actions/checkout@v2  
      
    - name: Install GCC  
      run: sudo apt-get update && sudo apt-get install -y gcc  
        
    - name: Compile dirtycow.c  
      run: gcc -pthread dirtycow.c -o dirtycow -lcrypt  

