name: Compile Hello World in C  
  
on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
    - uses: actions/checkout@v2  
      
    - name: Install GCC  
      run: sudo apt-get update && sudo apt-get install -y gcc  
        
    - name: Compile hello.c  
      run: gcc -o hello hello.c  
        
    - name: Run hello  
      run: ./hello